/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

const char *lily_dynaload_table[] = {
    "\1Interpreter\0"
    ,"C\6Interpreter"
    ,"m\0<new>\0:Interpreter"
    ,"m\0error\0(Interpreter):String"
    ,"m\0error_message\0(Interpreter):String"
    ,"m\0parse_expr\0(Interpreter,String,String):Option[String]"
    ,"m\0parse_file\0(Interpreter,String):Boolean"
    ,"m\0parse_string\0(Interpreter,String,String):Boolean"
    ,"Z"
};
