/* Contents autogenerated by dyna_tools.py */
const char *lily_dynaload_table[] = {
    "\01Interpreter\0"
    ,"C\05Interpreter"
    ,"m:<new>\0:Interpreter"
    ,"m:error\0(Interpreter):String"
    ,"m:parse_expr\0(Interpreter,String,String):Option[String]"
    ,"m:parse_file\0(Interpreter,String):Boolean"
    ,"m:parse_string\0(Interpreter,String,String):Boolean"
    ,"Z"
};
