/* Contents autogenerated by dyna_tools.py */
#define ARG_Interpreter(state, index) \
(lily_spawni_Interpreter *)lily_arg_generic(s, index)

#define ID_Interpreter(state) lily_cid_at(state, 0)

#define INIT_Interpreter(state, target) \
target = lily_malloc(sizeof(lily_spawni_Interpreter)); \
target->refcount = 0; \
target->destroy_func = (lily_destroy_func)destroy_Interpreter;
